import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import {Container} from "@/components/Home/NavBar/Container";
import Footer from "@/components/Home/Footer/Footer";
import {SupabaseProvider} from "@/context/SupabaseContext";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Gallery app",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={`${inter.className} dark`}>
          <SupabaseProvider>
            <>
                <Container/>
                {children}
                <Footer />
            </>
          </SupabaseProvider>
      </body>
    </html>
  );
}
